repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort .
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black .
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy . --disallow-untyped-defs
        types: [python]
        pass_filenames: false

#      - id: pydocstyle
#        name: pydocstyle
#        stages: [commit]
#        language: system
#        entry: poetry run pydocstyle
#        types: [python]
#        pass_filenames: false

      - id: pytest-cov
        name: pytest-cov
        stages: [push]
        language: system
        entry: poetry run python -m pytest
        types: [python]
        pass_filenames: false