[tool.poetry]
name = "az-static-web-app-docs-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.9"
mkdocs = "^1.1.2"
mkdocs-material = "^8.2.6"
mkdocs-git-revision-date-plugin = "^0.3.1"
mkdocs-macros-plugin = "^0.5.0"
mkdocs-mermaid2-plugin = "^0.5.1"
myst-parser = "^0.17.0"
sphinx = "^3.2.1"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^21.12b0"
mypy = "^0.910"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
